export interface EyecandyTechnique {
  id: string;
  name: string;
  category: "Camera & Rigging" | "Optics & Lens FX" | "Perspective & Staging" | "Lighting & Atmosphere" | "Editing, Time & Motion" | "Stylistic & Digital";
  definition: string;
  visualCues: string;
  cinematicExample: string;
}

export const EYECANDY_TECHNIQUES: EyecandyTechnique[] = [
  // Camera & Rigging
  {
    id: "bolt-cam",
    name: "BOLT CAM",
    category: "Camera & Rigging",
    definition: "Ultra high-speed robotic arm cinema camera executing millimeter-precise, lightning-fast kinetic moves impossible for human operators.",
    visualCues: "Instantaneous whip acceleration, extreme macro liquid splashes, repeatable high-speed trajectory.",
    cinematicExample: "High-speed tabletop commercials, fast action sequences (Sherlock Holmes, Michael Bay films).",
  },
  {
    id: "dolly-zoom",
    name: "DOLLY ZOOM",
    category: "Camera & Rigging",
    definition: "Simultaneous optical zoom in while physically dollying backward (or vice versa), warping background perspective while foreground subject scale remains identical.",
    visualCues: "Vertigo perspective warp, background rushing toward or receding from subject, psychological disorientation.",
    cinematicExample: "Vertigo (Alfred Hitchcock), Jaws (Steven Spielberg), Goodfellas (Martin Scorsese).",
  },
  {
    id: "double-dolly",
    name: "DOUBLE DOLLY",
    category: "Camera & Rigging",
    definition: "Both the camera and the actor ride on the same moving dolly track together, making the character appear frozen while the world slides behind them.",
    visualCues: "Floating character sensation, uncanny dissociation from moving surroundings.",
    cinematicExample: "Spike Lee signature shot (Malcolm X, 25th Hour, BlacKkKlansman).",
  },
  {
    id: "snorricam",
    name: "SNORRICAM",
    category: "Camera & Rigging",
    definition: "Rig strapped directly to the actor's chest or waist with the camera pointed right into their face, keeping their head statically centered as the background violently shakes.",
    visualCues: "Intense claustrophobia, panic, drunkenness or altered consciousness, static head with shifting background.",
    cinematicExample: "Requiem for a Dream (Darren Aronofsky), Mean Streets, The Revenant.",
  },
  {
    id: "fpv-drone",
    name: "FPV DRONE",
    category: "Camera & Rigging",
    definition: "First-person view acrobatic drone plunging through narrow corridors, diving skyscrapers, or racing inches above vehicles at 100+ mph.",
    visualCues: "Extreme rotational speed, zero-gravity barrel rolls, diving vertical drops, visceral acrobatics.",
    cinematicExample: "Ambulance (Michael Bay), Red Bull cinema, Mission: Impossible.",
  },
  {
    id: "arc",
    name: "ARC",
    category: "Camera & Rigging",
    definition: "Circular 360-degree tracking rotation around a stationary or moving subject, elevating romantic revelation, tension, or confrontation.",
    visualCues: "Fluid 360 rotation, continuously shifting background panorama while subject remains pivotal axis.",
    cinematicExample: "The Avengers assemble hero shot (Joss Whedon), De Palma thrillers, Matrix standoffs.",
  },
  {
    id: "camera-roll",
    name: "CAMERA ROLL",
    category: "Camera & Rigging",
    definition: "Continuous rotational spin along the lens optical Z-axis, inverting the horizon completely upside down.",
    visualCues: "Inverting horizon line, disorienting centrifugal vortex sensation.",
    cinematicExample: "First Man, Top Gun: Maverick, Into the Spider-Verse.",
  },
  {
    id: "crash-cut",
    name: "CRASH CUT",
    category: "Camera & Rigging",
    definition: "Abrupt, startling optical crash or violent instantaneous cut from extreme quiet into sonic and visual fury.",
    visualCues: "High-contrast dynamic shock, jarring audio-visual juxtaposition.",
    cinematicExample: "Kill Bill (Quentin Tarantino), Edgar Wright films.",
  },
  {
    id: "whip-pan",
    name: "WHIP PAN",
    category: "Camera & Rigging",
    definition: "Extremely fast horizontal camera swivel blurring all intermediate detail into motion streaks, used to hide transitions or snap between subjects.",
    visualCues: "Horizontal directional blur, energetic rhythmic transition, rapid ping-pong dialogue framing.",
    cinematicExample: "La La Land, Whiplash (Damien Chazelle), Boogie Nights.",
  },
  {
    id: "lazy-susan",
    name: "LAZY SUSAN",
    category: "Camera & Rigging",
    definition: "Rotating turntable revolving subjects or objects 360 degrees against fixed or contrasting backdrops.",
    visualCues: "Graceful motorized axial revolution, 3D product or character presentation.",
    cinematicExample: "High-fashion editorials, music videos, The Matrix bullet reflections.",
  },
  {
    id: "tracking",
    name: "TRACKING",
    category: "Camera & Rigging",
    definition: "Camera physically moves alongside, leading, or trailing subjects through spaces across long contiguous takes.",
    visualCues: "Immersive spatial continuity, walking alongside characters across complex architectural environments.",
    cinematicExample: "1917, Goodfellas Copacabana long take, The Shining hallway tricycle.",
  },
  {
    id: "trucking",
    name: "TRUCKING",
    category: "Camera & Rigging",
    definition: "Lateral horizontal tracking movement following characters parallel to their vector of travel.",
    visualCues: "Side-scrolling visual momentum, profile view motion against parallax background layers.",
    cinematicExample: "Wes Anderson lateral set tracking, Oldboy corridor fight.",
  },
  {
    id: "pedestal",
    name: "PEDESTAL",
    category: "Camera & Rigging",
    definition: "Physical vertical elevation of the entire camera rig straight up or down without altering lens pitch angle.",
    visualCues: "Towering reveal of subject stature, elevating vertically over obstacles.",
    cinematicExample: "Stanley Kubrick reveals, superhero reveals.",
  },
  {
    id: "pass-through",
    name: "PASS THROUGH",
    category: "Camera & Rigging",
    definition: "Impossible camera glide traversing seamlessly through glass windows, keyholes, car windshields, or narrow grates.",
    visualCues: "Boundless camera liberation, defying physical spatial boundaries.",
    cinematicExample: "Panic Room, Contact (Robert Zemeckis mirror scene).",
  },
  {
    id: "wandering",
    name: "WANDERING",
    category: "Camera & Rigging",
    definition: "Camera drifts away from the primary character, exploring ambient background details, secondary characters, or architecture before re-anchoring.",
    visualCues: "Lyrical, detached, poetic camera curiosity unmoored from conventional dialogue editing.",
    cinematicExample: "Terrence Malick films (The Tree of Life), Tarkovsky.",
  },
  {
    id: "locked-on",
    name: "LOCKED-ON",
    category: "Camera & Rigging",
    definition: "Digital or motorized stabilization locking rigidly to a single feature (eye, chest, vehicle wheel) while the rest of the frame vibrates wildly.",
    visualCues: "Rigidly anchored focal point with kinetic, shaking peripheral surroundings.",
    cinematicExample: "Sherlock Holmes punch sequences, sports montages.",
  },
  {
    id: "conveyor",
    name: "CONVEYOR",
    category: "Camera & Rigging",
    definition: "Continuous, mechanized linear travel evoking assembly lines, treadmill runners, or endless motorized transit.",
    visualCues: "Industrial hypnotic rhythm, uniform linear momentum.",
    cinematicExample: "Modern Times (Charlie Chaplin), OK Go music videos.",
  },
  {
    id: "aerial",
    name: "AERIAL",
    category: "Camera & Rigging",
    definition: "Sweeping high-altitude birds-eye perspectives from helicopter, drone, or aircraft establishing geographical and environmental scale.",
    visualCues: "Expansive vista horizons, diminishing human scale, topographical majesty.",
    cinematicExample: "The Shining opening road drive, Sicario border convoy.",
  },
  {
    id: "fixed-cam",
    name: "FIXED CAM",
    category: "Camera & Rigging",
    definition: "Unmoving tripod lock-off letting characters enter, interact, and exit the frame freely without camera intervention.",
    visualCues: "Objective observational detachment, theatrical framing, rigorous discipline.",
    cinematicExample: "Yasujiro Ozu, Roy Andersson, Michael Haneke.",
  },
  {
    id: "handheld",
    name: "HANDHELD",
    category: "Camera & Rigging",
    definition: "Unstabilized human camera operation capturing organic micro-tremors, immediacy, and chaotic documentary authenticity.",
    visualCues: "Spontaneous reactive framing, kinetic urgency, visceral intimacy.",
    cinematicExample: "The Bourne Supremacy, Succession, Children of Men.",
  },

  // Optics & Lens FX
  {
    id: "split-diopter",
    name: "SPLIT DIOPTER",
    category: "Optics & Lens FX",
    definition: "Half-convex optical element placed over half the lens, enabling simultaneous razor-sharp focus on both an extreme foreground element and distant background.",
    visualCues: "Impossible simultaneous near/far depth of field, subtle vertical blurring seam dividing the frame.",
    cinematicExample: "Carrie, The Thing (John Carpenter), Blow Out (Brian De Palma).",
  },
  {
    id: "tilt-shift",
    name: "TILT SHIFT",
    category: "Optics & Lens FX",
    definition: "Tilting and shifting lens plane relative to the camera sensor (Scheimpflug principle), creating a miniature diorama effect with a narrow slice of focus.",
    visualCues: "Toy-like miniaturization, dramatic non-parallel blur planes, miniature town look.",
    cinematicExample: "The Social Network regatta boat race, Gulliver's Travels.",
  },
  {
    id: "bullet-time",
    name: "BULLET TIME",
    category: "Optics & Lens FX",
    definition: "High-speed camera array freezing an ultra-fast event in time while the camera swoops smoothly 360 degrees around the frozen action.",
    visualCues: "Frozen raindrops, suspended mid-air combatants, impossible temporal manipulation.",
    cinematicExample: "The Matrix (Wachowskis), Swordfish.",
  },
  {
    id: "fisheye",
    name: "FISHEYE",
    category: "Optics & Lens FX",
    definition: "Curvilinear ultra-wide lens creating extreme barrel distortion with 180-degree spherical perspective.",
    visualCues: "Extreme curved edges, bulbous bulging centers, surreal claustrophobic warp.",
    cinematicExample: "The Favourite (Yorgos Lanthimos), 90s Hype Williams hip-hop music videos, Fallen Angels.",
  },
  {
    id: "probe",
    name: "PROBE",
    category: "Optics & Lens FX",
    definition: "Long waterproof tubular periscope probe lens sneaking inside microscopic crevices, insect tunnels, beverage glasses, or computer circuit boards.",
    visualCues: "Impossible insect-perspective journeys through microscopic tubes and slots.",
    cinematicExample: "Laowa Probe lens cinematography, David Fincher macro inserts.",
  },
  {
    id: "halation",
    name: "HALATION",
    category: "Optics & Lens FX",
    definition: "Warm reddish-orange photochemical glow bleeding around intense specular highlights where light scatters through photographic film layers.",
    visualCues: "Ethereal warm red/orange bloom around lamps, direct sun, or neon fixtures.",
    cinematicExample: "Kodak 35mm film emulation, Dune, Oppenheimer, Euphoria.",
  },
  {
    id: "shallow-focus",
    name: "SHALLOW FOCUS",
    category: "Optics & Lens FX",
    definition: "Extremely narrow depth of field isolating subject with lush creamy bokeh, obliterating distracting backgrounds.",
    visualCues: "Soft buttery background orbs, razor-thin focal plane resting precisely on actor's eyelashes.",
    cinematicExample: "Amélie, Barry Lyndon (f/0.7 Zeiss lenses), Portrait of a Lady on Fire.",
  },
  {
    id: "focal-shift",
    name: "FOCAL SHIFT",
    category: "Optics & Lens FX",
    definition: "Rack focus pulling clarity smoothly from foreground object to background character to guide audience attention.",
    visualCues: "Dynamic transfer of optical clarity across spatial depths during continuous action.",
    cinematicExample: "Casino Royale, Parasite, Seven.",
  },
  {
    id: "distortions",
    name: "DISTORTIONS",
    category: "Optics & Lens FX",
    definition: "Intentional optical aberrations, prism splitters, anamorphic streak flaring, or vintage lens fringing.",
    visualCues: "Chromatic aberration, blue horizontal anamorphic flares, swirling swirly bokeh (Petzval).",
    cinematicExample: "Poor Things, Star Trek (J.J. Abrams), Batman.",
  },
  {
    id: "vignette",
    name: "VIGNETTE",
    category: "Optics & Lens FX",
    definition: "Subtle optical or digital darkening of peripheral corners, directing viewer gaze directly into frame center.",
    visualCues: "Shadowed outer border framing, vintage lens falloff look.",
    cinematicExample: "The Lighthouse, 19th-century period pieces.",
  },
  {
    id: "magnification",
    name: "MAGNIFICATION",
    category: "Optics & Lens FX",
    definition: "Extreme optical macro telephoto lens revealing cellular textures, iris pupils, or mechanical watch escapements.",
    visualCues: "Microscopic detail magnified into towering cinematic scale.",
    cinematicExample: "Oppenheimer particle montages, Fight Club opening brain neuron travel.",
  },
  {
    id: "reflections",
    name: "REFLECTIONS",
    category: "Optics & Lens FX",
    definition: "Framing through puddles, mirrored glass, wet asphalt, or polished sunglasses to capture dual visual layers.",
    visualCues: "Layered reality, split duality, neon reflections on wet urban surfaces.",
    cinematicExample: "Taxi Driver, Blade Runner, Drive (Nicolas Winding Refn).",
  },

  // Perspective & Staging
  {
    id: "central-framing",
    name: "CENTRAL FRAMING",
    category: "Perspective & Staging",
    definition: "Placing subjects dead-center in the composition with mathematical symmetry, evoking divine authority or obsession.",
    visualCues: "Perfect bilateral symmetry, hypnotic one-point perspective corridor convergence.",
    cinematicExample: "Stanley Kubrick (The Shining, 2001), Wes Anderson (The Grand Budapest Hotel).",
  },
  {
    id: "dutch-angle",
    name: "DUTCH ANGLE",
    category: "Perspective & Staging",
    definition: "Canted camera tilt off the horizontal axis, visually signaling psychological unease, madness, or moral corruption.",
    visualCues: "Diagonal horizon, off-kilter world, visceral discomfort.",
    cinematicExample: "The Third Man, Batman (1966 & 1989), 12 Monkeys.",
  },
  {
    id: "tableau",
    name: "TABLEAU",
    category: "Perspective & Staging",
    definition: "Static, painterly, theatrical composition where characters are choreographed like a living painting or stage set.",
    visualCues: "Flat theatrical frontal staging, immaculately dressed art direction, tableau vivant.",
    cinematicExample: "Peter Greenaway, Wes Anderson, Roy Andersson.",
  },
  {
    id: "object-pov",
    name: "OBJECT POV",
    category: "Perspective & Staging",
    definition: "Camera positioned as if looking out from inside an inanimate object: refrigerator, car trunk, washing machine, or toilet.",
    visualCues: "Looking out from inside boxes, car trunks, or microwave ovens at opening faces.",
    cinematicExample: "Quentin Tarantino (Pulp Fiction trunk shot), Breaking Bad (Walter White under floorboards).",
  },
  {
    id: "first-person",
    name: "FIRST-PERSON",
    category: "Perspective & Staging",
    definition: "Direct subjective POV showing the protagonist's hands, gun, or steering wheel in frame, mimicking video game optics.",
    visualCues: "Player hands entering frame bottom, subjective head bobbing, direct character eye-level.",
    cinematicExample: "Hardcore Henry, Doom, Peep Show.",
  },
  {
    id: "overhead",
    name: "OVERHEAD",
    category: "Perspective & Staging",
    definition: "God's eye 90-degree straight-down perspective flattening the 3D world into a geometric 2D graphic layout.",
    visualCues: "Top-down plan view, geometric labyrinth paths, human bodies laid flat.",
    cinematicExample: "Taxi Driver overhead carnage, Fargo snowy car park.",
  },
  {
    id: "worms-eye",
    name: "WORMS-EYE",
    category: "Perspective & Staging",
    definition: "Extreme ground-level upward camera angle looking up from dirt, floorboards, or pavement towards towering figures.",
    visualCues: "Towering stature, giant footwear crunching ground, imposing authority.",
    cinematicExample: "Citizen Kane low ceilings, Quentin Tarantino, anime hero reveals.",
  },
  {
    id: "fourth-wall",
    name: "FOURTH WALL",
    category: "Perspective & Staging",
    definition: "Character looks directly into the lens and addresses the audience, puncturing the cinematic illusion.",
    visualCues: "Direct eye contact with the viewer, intimate or ironic monologue address.",
    cinematicExample: "Fleabag, Ferris Bueller's Day Off, The Wolf of Wall Street, Deadpool.",
  },
  {
    id: "shadow-box",
    name: "SHADOW BOX",
    category: "Perspective & Staging",
    definition: "Framing subjects inside doorways, windows, archways, or vehicle cutouts creating deep frame-within-a-frame confinement.",
    visualCues: "Dark geometrical borders encasing illuminated subjects inside secondary openings.",
    cinematicExample: "The Searchers (John Ford doorway shot), In the Mood for Love.",
  },
  {
    id: "voyeur",
    name: "VOYEUR",
    category: "Perspective & Staging",
    definition: "Camera hidden behind blinds, leaves, door cracks, or fence railings spying on unsuspecting characters.",
    visualCues: "Obscured foreground elements, surveillance feeling, illicit observation.",
    cinematicExample: "Rear Window (Hitchcock), Blue Velvet (David Lynch in the closet).",
  },
  {
    id: "void",
    name: "VOID",
    category: "Perspective & Staging",
    definition: "Character or object isolated against an infinite, featureless pure black or pure white boundless negative space.",
    visualCues: "Floating subjects stripped of floor, walls, or environment, existential isolation.",
    cinematicExample: "Under the Skin black liquid void, Stranger Things sensory deprivation, Get Out sunken place.",
  },
  {
    id: "choreo",
    name: "CHOREO",
    category: "Perspective & Staging",
    definition: "Intricately synchronized ballet between camera operator and multiple moving actors across continuous uninterrupted timing.",
    visualCues: "Seamless dance-like staging, fluid rhythm without jumpy quick-edits.",
    cinematicExample: "John Wick, Atomic Blonde stairwell fight, Birdman.",
  },

  // Lighting & Atmosphere
  {
    id: "hard-light",
    name: "HARD LIGHT",
    category: "Lighting & Atmosphere",
    definition: "Un-diffused direct light casting sharp-edged, high-contrast shadows and specular gleams.",
    visualCues: "Crisp black shadow edges, dramatic Venetian blind shadow stripes, film noir chiaroscuro.",
    cinematicExample: "Double Indemnity, Blade Runner, Sin City.",
  },
  {
    id: "haze",
    name: "HAZE",
    category: "Lighting & Atmosphere",
    definition: "Atmospheric smoke, mist, or mineral haze catching light beams into visible glowing volumetric shafts.",
    visualCues: "God rays, visible light cones in smoky rooms, cinematic volumetric depth.",
    cinematicExample: "Blade Runner 2049, Alien, Denis Villeneuve films.",
  },
  {
    id: "silhouette",
    name: "SILHOUETTE",
    category: "Lighting & Atmosphere",
    definition: "Brightly lit background with completely unlit, pitch-black subject outlines, emphasizing graphic shape over interior detail.",
    visualCues: "Pitch black character silhouettes framed against sunset, fiery explosion, or illuminated windows.",
    cinematicExample: "Skyfall (Roger Deakins Shanghai fight), Django Unchained shootout.",
  },
  {
    id: "color-shift",
    name: "COLOR SHIFT",
    category: "Lighting & Atmosphere",
    definition: "Dynamic in-camera or grading transition shifting dominant chromatic spectrum across time (e.g. warm amber morphing to toxic green).",
    visualCues: "Color temperature metamorphosis signaling reality shifts or psychological degradation.",
    cinematicExample: "The Matrix (green tint vs real world blue), Traffic (Steven Soderbergh color grades).",
  },
  {
    id: "spotlight",
    name: "SPOTLIGHT",
    category: "Lighting & Atmosphere",
    definition: "Direct theatrical pool of circular illumination plunging the remainder of the stage or frame into deep blackness.",
    visualCues: "Theatrical solo illumination, isolated stage performer visual motif.",
    cinematicExample: "Chicago, Birdman, Joker.",
  },
  {
    id: "night-vision",
    name: "NIGHT VISION",
    category: "Lighting & Atmosphere",
    definition: "Monochromatic phosphor green or digital infrared glow with intense blown-out retinas and high video grain.",
    visualCues: "Phosphor green hue, luminous glowing pupils, tactical infrared illuminator flares.",
    cinematicExample: "The Silence of the Lambs basement climax, Zero Dark Thirty.",
  },
  {
    id: "thermal",
    name: "THERMAL",
    category: "Lighting & Atmosphere",
    definition: "Infrared heat-signature false-color palette mapping temperature gradations into rainbow spectrums.",
    visualCues: "Body heat false color (red/yellow hot against cool blue surroundings).",
    cinematicExample: "Predator, Sicario tunnel assault.",
  },
  {
    id: "magical-realism",
    name: "MAGICAL REALISM",
    category: "Lighting & Atmosphere",
    definition: "Lush, heightened, dreamlike naturalism where impossible, poetic visual elements are treated as mundane everyday occurrences.",
    visualCues: "Subtle surreal glows, golden halos, floating motes, impossible poetic coincidences.",
    cinematicExample: "Pan's Labyrinth (Guillermo del Toro), Big Fish, Amélie.",
  },
  {
    id: "dreamcore",
    name: "DREAMCORE",
    category: "Lighting & Atmosphere",
    definition: "Surreal, nostalgic, uncanny dream-state imagery featuring liminal spaces, heavy bloom, and faded color grading.",
    visualCues: "Soft focus glow, liminal architecture, melancholic pastel tint, drifting perspective.",
    cinematicExample: "Twin Peaks, Donnie Darko, Eternal Sunshine of the Spotless Mind.",
  },
  {
    id: "dystopian",
    name: "DYSTOPIAN",
    category: "Lighting & Atmosphere",
    definition: "Oppressive desaturated industrial palettes dominated by rust, asphalt, toxic amber haze, and concrete grays.",
    visualCues: "Smoggy skies, brutalist concrete architecture, rain-slicked asphalt, neon decay.",
    cinematicExample: "Children of Men, Blade Runner 2049, Brazil.",
  },

  // Editing, Time & Motion
  {
    id: "speed-ramp",
    name: "SPEED RAMP",
    category: "Editing, Time & Motion",
    definition: "Fluid acceleration or deceleration between normal 24fps and ultra-slow 240fps motion within the same uninterrupted shot.",
    visualCues: "Action starts slow, snaps instantaneously to high speed on impact, then floats back to slow-mo.",
    cinematicExample: "300 (Zack Snyder), Guy Ritchie action brawls, The Matrix Reloaded.",
  },
  {
    id: "step-print",
    name: "STEP-PRINT",
    category: "Editing, Time & Motion",
    definition: "Duplicating frames shot at low shutter speeds, producing ethereal, smeared light trails and rhythmic staccato motion.",
    visualCues: "Luminous light smears trailing moving actors, hypnotic drunken tempo.",
    cinematicExample: "Chungking Express, Fallen Angels (Wong Kar-wai & Christopher Doyle).",
  },
  {
    id: "match-cut",
    name: "MATCH CUT",
    category: "Editing, Time & Motion",
    definition: "Juxtaposition of two distinct scenes linked by identical compositional geometry, graphic shape, or motion trajectory.",
    visualCues: "Bone morphing into spaceship, spinning ceiling fan morphing into helicopter blades.",
    cinematicExample: "2001: A Space Odyssey (bone to satellite), Lawrence of Arabia (match to desert sunrise).",
  },
  {
    id: "jump-cut",
    name: "JUMP CUT",
    category: "Editing, Time & Motion",
    definition: "Successive shots of the same subject with minor, jarring camera angle changes, fracturing temporal continuity.",
    visualCues: "Stuttering passage of time, anxious energetic temporal leaps.",
    cinematicExample: "Breathless (Jean-Luc Godard), The Royal Tenenbaums bathroom mirror cut.",
  },
  {
    id: "flash-cut",
    name: "FLASH CUT",
    category: "Editing, Time & Motion",
    definition: "Subliminal 1-to-3 frame instantaneous image flash puncturing the primary scene, conveying trauma or revelation.",
    visualCues: "Subliminal eye blink flash, shocking psychological memory intrusion.",
    cinematicExample: "The Exorcist demon face flashes, Fight Club single-frame Tyler Durden splices.",
  },
  {
    id: "freeze-frame",
    name: "FREEZE FRAME",
    category: "Editing, Time & Motion",
    definition: "Halting motion entirely on a single keyframe while narration, titles, or music continue, immortalizing a pivotal moment.",
    visualCues: "Suspended motion snapshot, iconic narrative punctum.",
    cinematicExample: "The 400 Blows closing freeze, Goodfellas (\"As far back as I can remember...\").",
  },
  {
    id: "infinite-loop",
    name: "INFINITE LOOP",
    category: "Editing, Time & Motion",
    definition: "Perfect seamless cyclical motion where the ending keyframe loops invisibly back into the starting frame.",
    visualCues: "Mesmerizing endless rotation or perpetual action cycle.",
    cinematicExample: "Cinemagraphs, modern viral music video loops.",
  },
  {
    id: "stop-motion",
    name: "STOP MOTION",
    category: "Editing, Time & Motion",
    definition: "Physical objects or puppets adjusted frame by frame, giving tangible materials tactile, stuttering physical life.",
    visualCues: "Tactile clay/puppet textures, charming mechanical stepped motion cadence.",
    cinematicExample: "Guillermo del Toro's Pinocchio, Coraline, Isle of Dogs.",
  },
  {
    id: "boomerang",
    name: "BOOMERANG",
    category: "Editing, Time & Motion",
    definition: "Rapid playback of a short motion sequence forward and then instantly backward in a seamless bounce loop.",
    visualCues: "Oscillating visual stutter, elastic kinetic repetition.",
    cinematicExample: "Music videos, modern experimental micro-editing.",
  },

  // Stylistic & Digital
  {
    id: "datamosh",
    name: "DATAMOSH",
    category: "Stylistic & Digital",
    definition: "Deliberately corrupting digital video compression I-frames, causing pixel motion vectors to bleed into subsequent scenes.",
    visualCues: "Melting pixels, surreal liquid compression glitches, psychedelic video artifacts.",
    cinematicExample: "A$AP Rocky - Yamborghini High music video, modern internet glitch art.",
  },
  {
    id: "split-screen",
    name: "SPLIT SCREEN",
    category: "Stylistic & Digital",
    definition: "Dividing the frame into multiple simultaneous panels showing concurrent action or multiple character perspectives.",
    visualCues: "Dual or multi-window cinematic layout, concurrent chronological events.",
    cinematicExample: "Requiem for a Dream, 500 Days of Summer, De Palma thrillers.",
  },
  {
    id: "floating-ui",
    name: "FLOATING UI",
    category: "Stylistic & Digital",
    definition: "Diegetic or holographic user interface graphics tracking directly to actors' vision or spatial environment.",
    visualCues: "Augmented reality overlays, glowing holographic data floating in 3D perspective.",
    cinematicExample: "Iron Man HUD, Minority Report, Sherlock Holmes analytical text.",
  },
  {
    id: "slit-scan",
    name: "SLIT-SCAN",
    category: "Stylistic & Digital",
    definition: "Exposing a sliver of film or sensor row over continuous time, creating streaking, undulating warp tunnels.",
    visualCues: "Hypnotic warp tunnel, psychedelic streaking temporal vortex.",
    cinematicExample: "2001: A Space Odyssey Stargate sequence, Doctor Who intros.",
  },
  {
    id: "collage",
    name: "COLLAGE",
    category: "Stylistic & Digital",
    definition: "Layering disparate archival footage, paper cutouts, sketches, and live action into a rich multimedia tapestry.",
    visualCues: "Scrapbook aesthetic, varied frame rates, torn paper edges, mixed aspect ratios.",
    cinematicExample: "Spider-Man: Into the Spider-Verse, Monty Python animations.",
  },
  {
    id: "ratio-switch",
    name: "RATIO SWITCH",
    category: "Stylistic & Digital",
    definition: "Dynamic shifting of the aspect ratio (e.g. 4:3 Academy to 2.39:1 Anamorphic) during a shot to signify narrative expansion.",
    visualCues: "Expanding or contracting black letterbox bars opening into panoramic spectacle.",
    cinematicExample: "The Grand Budapest Hotel, Mommy (Xavier Dolan), The Hunger Games: Catching Fire.",
  },
  {
    id: "pixel-art",
    name: "PIXEL ART",
    category: "Stylistic & Digital",
    definition: "Retro video game raster aesthetic with visible chunky 8-bit or 16-bit pixel grids and limited color palettes.",
    visualCues: "Chunky square pixels, nostalgic arcade aesthetic, chiptune motion.",
    cinematicExample: "Scott Pilgrim vs. the World, Wreck-It Ralph.",
  },
  {
    id: "photogrammetry",
    name: "PHOTOGRAMMETRY",
    category: "Stylistic & Digital",
    definition: "Reconstructing real-world environments from hundreds of photos into point-clouds or 3D meshes with ghostly scan artifacts.",
    visualCues: "Particle point clouds, ethereal transparent 3D scans, lidar aesthetic.",
    cinematicExample: "Radiohead - House of Cards, The Matrix Resurrections code scans.",
  },
];

export const EYECANDY_CATEGORIES = [
  "All Techniques",
  "Camera & Rigging",
  "Optics & Lens FX",
  "Perspective & Staging",
  "Lighting & Atmosphere",
  "Editing, Time & Motion",
  "Stylistic & Digital",
] as const;

export function searchEyecandyTechniques(query: string, category: string = "All Techniques"): EyecandyTechnique[] {
  let filtered = EYECANDY_TECHNIQUES;
  if (category !== "All Techniques") {
    filtered = filtered.filter((t) => t.category === category);
  }
  if (!query.trim()) return filtered;
  const q = query.toLowerCase();
  return filtered.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.definition.toLowerCase().includes(q) ||
      t.visualCues.toLowerCase().includes(q) ||
      t.cinematicExample.toLowerCase().includes(q)
  );
}
